/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//**************************************************************************************//
package personal_finance_tracker;
//*************************************************//

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author dylan
 */
//*************************************************//
public class Delete_Expenditure extends javax.swing.JFrame {
    //*************************************************//
    /**
     * Creates new form Edit_Expenditure
     */
    //*************************************************//
    
    //*************************************************//
    //create expenditure object
    private ExpenditureOrganiser expenditure;
    private ArrayList<ExpenditureOrganiser> array;
    private int indexOfTarget;
    //*************************************************//
    
    //*************************************************//
    public Delete_Expenditure() {
        initComponents();
        expenditure = new ExpenditureOrganiser();
        
        //*************************************************//
        //create a list of all expenditures
        array = new ArrayList<ExpenditureOrganiser>();
        array = expenditure.listOfExpenditures();
        //*************************************************//
    }
    //*************************************************//
        
    //*************************************************//
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //*************************************************//
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblEdit = new javax.swing.JLabel();
        txtTargetToEdit = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnBack2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delete Expenditure");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setText("Delete an Expenditure:");

        lblEdit.setText("Enter the name of the expenditure you wish to delete:");

        btnSave.setText("Delete Expenditure");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack2.setText("Back");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave))
                    .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTargetToEdit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTargetToEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBack2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        //*************************************************//
        //code to delete an expenditure from the list and update the list
        String target = txtTargetToEdit.getText();
        while(target.isBlank())
        {
            //*************************************************//
            Personal_Finance_Tracker.textToSpeech("... Warning");
            JOptionPane.showMessageDialog(null, "Error, target must contain a value.", "Error", JOptionPane.INFORMATION_MESSAGE);
            target = JOptionPane.showInputDialog(null, "Please enter the name you wish to search for:", "Enter name of Expenditure", JOptionPane.INFORMATION_MESSAGE);
            txtTargetToEdit.setText(target);
            //*************************************************//
        }
        //*************************************************//
        
        //*************************************************//
        //search through the list to find a match
        indexOfTarget = expenditure.findIndexByName(target);
        //*************************************************//
        
        //*************************************************//
        //if_ nothing is found
        if(indexOfTarget == -1)
        {
            //*************************************************//
            //no match found
            Personal_Finance_Tracker.textToSpeech("... Warning, " + target + " could not be found");
            JOptionPane.showMessageDialog(null, "'" + target + "' expenditure is not listed or could not be found :(");
            return;
            //*************************************************//
        }
        //continue if_ a match was found
        //*************************************************//
        
        //*************************************************//
        //display these values
        Personal_Finance_Tracker.textToSpeech("... Warning, " + target + " could not be found");
        JOptionPane.showMessageDialog(null, "'" + target + "' expenditure has been found");
        //*************************************************//
        
        //*************************************************//
        //remove old index of incorrect data
        array.remove(indexOfTarget);
        //*************************************************//
        
        //*************************************************//
        //update the text file
        expenditure.updateExpenditureFile(array);
        Personal_Finance_Tracker.textToSpeech("... delete successful");
        JOptionPane.showMessageDialog(null, "List has been updated successfully and delete successful", "Delete successful", JOptionPane.INFORMATION_MESSAGE);
        //*************************************************//
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        // TODO add your handling code here:

        //*************************************************//
        //go back to selection menu
        user_selection_window window = new user_selection_window();
        window.setVisible(true);
        dispose();
        //*************************************************//
    }//GEN-LAST:event_btnBack2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtTargetToEdit;
    // End of variables declaration//GEN-END:variables

}
//***********************************END OF FILE****************************************//