/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//**************************************************************************************//
package personal_finance_tracker;
//*************************************************//

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author dylan
 */
//*************************************************//
public class Edit_Expenditure extends javax.swing.JFrame {
    //*************************************************//
    /**
     * Creates new form Edit_Expenditure
     */
    //*************************************************//
    
    //*************************************************//
    //create expenditure object
    private ExpenditureOrganiser expenditure;
    private ArrayList<ExpenditureOrganiser> array;
    private int indexOfTarget;
    //*************************************************//
    
    //*************************************************//
    public Edit_Expenditure() {
        initComponents();
        expenditure = new ExpenditureOrganiser();
        
        //*************************************************//
        //create a list of all expenditures
        array = new ArrayList<ExpenditureOrganiser>();
        array = expenditure.listOfExpenditures();
        //*************************************************//
    }
    //*************************************************//
        
    //*************************************************//
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //*************************************************//
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblEdit = new javax.swing.JLabel();
        txtTargetToEdit = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblType = new javax.swing.JLabel();
        lblType1 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        cmbTypes = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Expenditure");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setText("Please select and make any edits to expenditures you have created below:");

        lblEdit.setText("Enter the name of the expenditure you wish to edit:");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblName.setText("Name:");

        lblType.setText("Type:");

        lblType1.setText("Amount:");

        btnSave.setText("Save Edited Expenditure");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        cmbTypes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbTypes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rent", "Food", "Utilities", "Transportation", "Savings/Debt", "Health", "Entertainment", "Personal Care", "Family and Education", "Miscellaneous" }));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave))
                    .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTargetToEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(lblType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAmount)
                                    .addComponent(lblType1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTargetToEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblType1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblType, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(cmbTypes))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
        //*************************************************//
        //get string from textfield to search for
        String target = txtTargetToEdit.getText();
        while(target.isBlank())
        {
            //*************************************************//
            Personal_Finance_Tracker.textToSpeech("... Warning, must contain a value");
            JOptionPane.showMessageDialog(null, "Error, target must contain value.", "Error", JOptionPane.INFORMATION_MESSAGE);
            target = JOptionPane.showInputDialog(null, "Please enter the name you wish to search for:", "Enter name of Expenditure", JOptionPane.INFORMATION_MESSAGE);
            txtTargetToEdit.setText(target);
            //*************************************************//
        }
        //*************************************************//
        
        //*************************************************//
        //search through the list to find a match
        indexOfTarget = expenditure.findIndexByName(target);
        //*************************************************//
        
        //*************************************************//
        //if_ nothing is found
        if(indexOfTarget == -1)
        {
            //*************************************************//
            //no match found
            Personal_Finance_Tracker.textToSpeech("... Warning, " + target + " could not be found");
            JOptionPane.showMessageDialog(null, "'" + target + "' expenditure is not listed or could not be found :(");
            txtAmount.setText("No match found");
            txtName.setText("No match found");
            cmbTypes.setSelectedIndex(0);
            return;
            //*************************************************//
        }
        //*************************************************//
        
        //*************************************************//
        //continue if_ they found the match
        String name = array.get(indexOfTarget).getName();
        String type = array.get(indexOfTarget).getType();
        String amount = array.get(indexOfTarget).getAmount();
        //*************************************************//
        
        //*************************************************//
        //display these values
        Personal_Finance_Tracker.textToSpeech("... found expenditure");
        JOptionPane.showMessageDialog(null, "'" + target + "' expenditure has been found");
        txtAmount.setText(amount);
        txtName.setText(name);
        cmbTypes.setSelectedItem(type);
        //*************************************************//
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
    //*************************************************//
    //save this data to the file
        
        //*************************************************//
        //get new values
        String newName = txtName.getText();
        //make sure the name is not greater than 20 characters
        if(newName.length() > 20)
        {
            Personal_Finance_Tracker.textToSpeech("... Warning, the name field must be less than 20 characters");
            JOptionPane.showMessageDialog(null, "Warning, the 'Name' field cannot be greater than 20 characters in length", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String newType = cmbTypes.getSelectedItem().toString();
        String newAmount = txtAmount.getText();
        //*************************************************//
        
        //*************************************************//
        //remove old index of incorrect data
        array.remove(indexOfTarget);
        //*************************************************//
        
        //*************************************************//
        //add new object
        ExpenditureOrganiser temp = new ExpenditureOrganiser(newName, newType, newAmount);
        array.add(temp);
        //*************************************************//
        
        //*************************************************//
        //save to text file
        expenditure.updateExpenditureFile(array);
        Personal_Finance_Tracker.textToSpeech("... Edit has been successfully saved");
        JOptionPane.showMessageDialog(null, "List has been updated successfully and new edit has been saved", "Edit successful", JOptionPane.INFORMATION_MESSAGE);
        //*************************************************//
        
    //*************************************************//
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        //*************************************************//
        //go back to selection menu
        user_selection_window window = new user_selection_window();
        window.setVisible(true);
        dispose();
        //*************************************************//
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbTypes;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblType1;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTargetToEdit;
    // End of variables declaration//GEN-END:variables

}
//***********************************END OF FILE****************************************//